### ISSUE TITLE
Is it works on osx ?

### ISSUE THREAD

**Issue by bsormagec** [Sunuba/roc#10]
Is it works on osx ? @Sunuba

**Comment by Sunuba** [comment]
It is os independent. Should work on osx

**Comment by bsormagec** [comment]
which version of python are u using ?

**Comment by bsormagec** [comment]
its returning error on pip install 

> ERROR: Could not find a version that satisfies the requirement pywin32==227 (from -r requirements.txt (line 104)) (from versions: none)
ERROR: No matching distribution found for pywin32==227 (from -r requirements.txt (line 104))

**Comment by Sunuba** [comment]
Mine is 3.6.5

**Comment by Sunuba** [comment]
I guess mac uses 2.7 by default. It won't work on that version.

**Comment by tehleet** [comment]
It doesn't work on Mac. I have working version on Mac, but it's a big mess for a PR. In few words, Mac Retina resolution needs a coordinates divided by 2.

https://medium.com/@tracy_blog/pyautogui-and-retina-displays-2d5c37a5aa5e

**Comment by bsormagec** [comment]
@tehleet if you create a new repo can you share me. I dont have any experience on pyton-ui apps.

**Comment by tehleet** [comment]
@bsormagec I doubt it. I currently doing it on Windows and more of coordinates based aproach. The fix isn't very hard, as I remember correctly, you just need in ImageCoordinate class devide by 2 returned coordinate

**Comment by bsormagec** [comment]
I didnt run this project on osx, is anybody run it on osx? and give me a repository url ?
